const ShopActionsTypes = {
    FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
    FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
    FETCH_COLLECTION_FAILURE: "FETCH_COLLECTION_FAILURE"
}

export default ShopActionsTypes